
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check_build_all:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: bazelbuild/setup-bazelisk@v2
      - name: Build target go
        run: cd go && bazel build //...
      - name: Build target grpc-gateway 
        run: cd grpc-gateway && bazel build //...
