
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  verify_descriptor:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: bazelbuild/setup-bazelisk@v2
      - name: Build proto descriptor
        run: bazel build //envoy/...

  verify_go:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: bazelbuild/setup-bazelisk@v2
      - name: Build target go
        run: cd go && bazel build //...

  verify_java:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: bazelbuild/setup-bazelisk@v2
      - name: Build target java
        run: cd java && bazel build //...